import org.junit.Test;

import com.asterionix.test.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'admin2' at '16.04.16 12:03' with Gradle 2.11
 *
 * @author admin2, @date 16.04.16 12:03
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
