package com.asterionix.test;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin2' at '16.04.16 12:03' with Gradle 2.11
 *
 * @author admin2, @date 16.04.16 12:03
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
}

